# Generated by Django 5.2.7 on 2025-10-22 09:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('api_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, help_text='The time when the log entry was created.')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], db_index=True, help_text='The severity level of the log entry.', max_length=10)),
                ('message', models.TextField(help_text='The log message.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='structured data associated with log entry')),
                ('application', models.ForeignKey(help_text='The application that sent the log entry.', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='logs.application')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['application', 'level', '-timestamp'], name='logs_logent_applica_2506fc_idx')],
            },
        ),
    ]
